#! /bin/sh

xautolock -time 15 -locker glitchlock -notify 20 -notifier "notify-send 'about to lock screen'" &
xautolock -time 20 -locker "xset dpms force off" &
rm $HOME/.config/dunst/dunststate &
sxhkd &
compton -bG -o 0 &
dunst &
thunar --daemon &
pkttyagent &
mopidy &

bspc monitor -d 一 二 三 四 五 六 七 八
#bspc monitor -d 1 2 3 4 5 6 7 8

. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color8"
bspc config active_border_color "$color9"
bspc config focused_border_color "$color9"
bspc config presel_feedback_color "$color1"

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Tilda state=floating
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam desktop='^8' follow=no split_dir=right
bspc rule -a Dota2 state=fullscreen follow=no
bspc rule -a discord desktop='^7'



polybar -r bar1 &
pasystray &
nm-applet &
tilda &
steam &
discord &
